services:
  # --- BACKEND ---
  backend:
    image: ghcr.io/unizar-30226-2026-11/backend:latest
    container_name: backend_app
    restart: always
    # Hace falta exponer el puerto al exterior, porque el navegador se conecta al backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env

  # --- FRONTEND ---
  frontend:
    image: ghcr.io/unizar-30226-2026-11/frontend:latest
    container_name: frontend_app
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env

  # --- REDIS (Caché/Sesiones) ---
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_server
    restart: always
    # No es estrictamente necesario exponer el puerto al exterior si solo el back lo usa
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: